export enum ClickActions {
  KITCHEN_EMPTY_SPOT,
  KITCHEN_CUPS,
  KITCHEN_CORN,
  KITCHEN_POT,
  KITCHEN_ELASTICS,
  KITCHEN_COOKIES,
  KITCHEN_CARPET,
  KITCHEN_PLASTERS,
  KITCHEN_GARBAGE,
  KITCHEN_CALENDER,
  KITCHEN_OVEN,
  KITCHEN_BALL,
  KITCHEN_BOARD,
  KITCHEN_DOOR,
  KITCHEN_LEFT_WINDOW,
  KITCHEN_RIGHT_WINDOW
}
